# Generated by Django 5.1.3 on 2024-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
